import type { Metadata } from "next";
// Evitar next/font remoto en build offline; usar stack del sistema
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
const geistSans = { variable: "--font-geist-sans" }
const geistMono = { variable: "--font-geist-mono" }

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
  <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
  <main>{children}</main>
  <Toaster position="top-right" richColors />


      </body>
    </html>
  );
}
